"""Add user_id to meal_templates

Revision ID: 0598a5c47f1c
Revises: 3456789abcde
Create Date: 2025-11-14 15:29:35.252251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0598a5c47f1c'
down_revision = '3456789abcde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('unique_user_meal_template', ['user_id', 'name', 'meal_type'])
        batch_op.create_foreign_key('fk_meal_templates_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_foods', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_food_code', ['user_id', 'code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_foods', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_food_code', type_='unique')

    with op.batch_alter_table('meal_templates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_meal_templates_user_id', type_='foreignkey')
        batch_op.drop_constraint('unique_user_meal_template', type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
