"""Make date nullable in diets table

Revision ID: 127f44e8a12b
Revises: 5bd48f369f7d
Create Date: 2025-11-14 16:49:26.754023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '127f44e8a12b'
down_revision = '5bd48f369f7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_diets')
    with op.batch_alter_table('diets', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_diet_date', ['user_id', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diets', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_diet_date', type_='unique')

    op.create_table('_alembic_tmp_diets',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('meals_data', sqlite.JSON(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='unique_user_diet_date')
    )
    # ### end Alembic commands ###
